### ISSUE TITLE
Java version error

### ISSUE THREAD

**Issue by crysper** [heroku/heroku-deploy#30]
I'm trying to deploy a rails app compiled with warbler gem to heroku.
I have the 1.8 version installed(and checked)

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/heroku/sdk/deploy/DeployWar : Unsupported major.minor version
51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: com.heroku.sdk.deploy.DeployWar. Program will exit.

**Comment by crysper** [comment]
Nevermind, my mistake, I had the wrong JRE path on cygwin

**Comment by jkutner** [comment]
This tool requires Java 7 or higher locally.
