### ISSUE TITLE
--jdk 7 doesn't work

### ISSUE THREAD

**Issue by cwong15** [heroku/heroku-deploy#33]
This is what I see if I specify JDK 1.7 instead of the default:

-----> Creating build...
       - file: slug.tgz
       - size: 39MB
-----> Uploading build...
       - success
-----> Deploying...
remote:
remote: -----> Fetching set buildpack https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/jvm-common.tgz... done
remote: -----> JVM Common app detected
remote: -----> Installing OpenJDK 7...curl: no URL specified!
remote: curl: try 'curl --help' or 'curl --manual' for more information
remote:
remote:  !     Push rejected, failed to compile JVM Common app
remote:
Exception in thread "main" java.lang.RuntimeException: The build failed
        at com.heroku.sdk.deploy.BuildsDeployer.deploySlug(BuildsDeployer.java:118)
        at com.heroku.sdk.deploy.Deployer.createAndReleaseSlug(Deployer.java:108)
        at com.heroku.sdk.deploy.Deployer.deploy(Deployer.java:69)
        at com.heroku.sdk.deploy.App.deploy(App.java:57)
        at com.heroku.sdk.deploy.App.deploy(App.java:61)
        at com.heroku.sdk.deploy.WarApp.deploy(WarApp.java:30)
        at com.heroku.sdk.deploy.DeployWar.main(DeployWar.java:70)

**Comment by jkutner** [comment]
Try using `--jdk 1.7`. I think the command docs are just wrong.
