### ISSUE TITLE
deploy:jar does not work behind proxy

### ISSUE THREAD

**Issue by cobour** [heroku/heroku-deploy#34]
Hi,
I am working on a Windows 7 PC behind a corporate proxy.
HTTP_PROXY and HTTPS_PROXY env vars are set and correct.
The command "heroku login" works. But when I issue the command
"heroku deploy:jar --jar target/*.war --app MY_APP_NAME_HERE"
I get the stacktrace which I copied to the bottom of my post.

Deploying with my laptop (direct access to the internet) works fine using the same command.

Any hints?

Regards
Frank

---- Stacktrace---

Exception in thread "main" org.apache.http.conn.HttpHostConnectException: Connect to api.heroku.com:443 [api.heroku.com/184.72.252.139, api.heroku.com/184.73.210.26, api.heroku.com/107.2
1.218.33] failed: Connection timed out: connect                                                                                                                                           
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)                                                            
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)                                                              
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)                                                                                          
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)                                                                                                 
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)                                                                                                     
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)                                                                                                            
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)                                                                                                     
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)                                                                                          
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)                                                                                           
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)                                                                                          
        at com.heroku.sdk.deploy.utils.RestClient.get(RestClient.java:29)                                                                                                                 
        at com.heroku.sdk.deploy.ConfigVars.getConfigVars(ConfigVars.java:41)                                                                                                             
        at com.heroku.sdk.deploy.ConfigVars.merge(ConfigVars.java:24)                                                                                                                     
        at com.heroku.sdk.deploy.Deployer.mergeConfigVars(Deployer.java:103)                                                                                                              
        at com.heroku.sdk.deploy.Deployer.deploy(Deployer.java:67)                                                                                                                        
        at com.heroku.sdk.deploy.App.deploy(App.java:57)                                                                                                                                  
        at com.heroku.sdk.deploy.App.deploy(App.java:61)                                                                                                                                  
        at com.heroku.sdk.deploy.DeployJar.deploy(DeployJar.java:29)                                                                                                                      
        at com.heroku.sdk.deploy.DeployJar.main(DeployJar.java:104)                                                                                                                       
Caused by: java.net.ConnectException: Connection timed out: connect                                                                                                                       
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)                                                                                                                      
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)                                                                                              
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)                                                                                                   
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)                                                                                            
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)                                                                                                     
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)                                                                                                                     
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)                                                                                                                     
        at java.net.Socket.connect(Socket.java:589)                                                                                                                                       
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:338)                                                                         
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)                                                            
        ... 18 more

**Comment by jkutner** [comment]
Can you try setting the following environment variable:

```
set JAVA_TOOL_OPTIONS="-DsocksProxyHost=<HTTPS_PROXY_HOST> -DsocksProxyPort=<HTTPS_PROXY_PORT>"
```

Then run the plugin again.

If that does not work try setting it like this and deploy again:

```
set JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=<HTTPS_PROXY_HOST> -Dhttp.proxyPort=<HTTPS_PROXY_PORT>"
```

I actually don't think either of those will work, but it's worth a try.

If they do not work, we will need to update the plugin to obey HTTP_PROXY and HTTPS_PROXY.

**Comment by cobour** [comment]
Hi,
the first option threw another exception (see below), the second option timed out (see my first post). I also added 
```
-Djava.net.socks.username=MY_USERID -Djava.net.socks.password=MY_PW       (option 1)
-Dhttp.proxyUser=MY_USERID -Dhttp.proxyPassword=MY_PW       (option 2)
```
Regards
Frank

----------------- Exception --------------------
```
heroku deploy:jar --jar target/*.war --app MY_APP_NAME_HERE

Uploading target/sekproto-0.1.0.war....
Picked up JAVA_TOOL_OPTIONS: "-DsocksProxyHost=proxy.pnw.loc -DsocksProxyPort=8080 -Djava.net.socks.username=MY_USERID -Djava.net.socks.password=MY_PW"
-----> Packaging application...
       - app: MY_APP_NAME_HERE
       - including: target/MY_APP_NAME_HERE-0.1.0.war
Feb 10, 2016 4:01:50 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.heroku.com:443: Can't connect to SOCKS proxy:proxy.pnw.loc -DsocksProxyPort=8080 -Djava.net.socks.username=MY_USERID -Djava.net.socks.password=MY_PW
Feb 10, 2016 4:01:50 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: Retrying request to {s}->https://api.heroku.com:443
Feb 10, 2016 4:01:50 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.heroku.com:443: Can't connect to SOCKS proxy:proxy.pnw.loc -DsocksProxyPort=8080 -Djava.net.socks.username=MY_USERID -Djava.net.socks.password=MY_PW
Feb 10, 2016 4:01:50 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: Retrying request to {s}->https://api.heroku.com:443
Feb 10, 2016 4:01:50 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.heroku.com:443: Can't connect to SOCKS proxy:proxy.pnw.loc -DsocksProxyPort=8080 -Djava.net.socks.username=MY_USERID -Djava.net.socks.password=MY_PW
Feb 10, 2016 4:01:50 PM org.apache.http.impl.execchain.RetryExec execute
INFORMATION: Retrying request to {s}->https://api.heroku.com:443
Exception in thread "main" java.net.SocketException: Can't connect to SOCKS proxy:proxy.pnw.loc -DsocksProxyPort=8080 -Djava.net.socks.username=MY_USERID -Djava.net.socks.password=MY_PW
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:338)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.heroku.sdk.deploy.utils.RestClient.get(RestClient.java:29)
        at com.heroku.sdk.deploy.ConfigVars.getConfigVars(ConfigVars.java:41)
        at com.heroku.sdk.deploy.ConfigVars.merge(ConfigVars.java:24)
        at com.heroku.sdk.deploy.Deployer.mergeConfigVars(Deployer.java:103)
        at com.heroku.sdk.deploy.Deployer.deploy(Deployer.java:67)
        at com.heroku.sdk.deploy.App.deploy(App.java:57)
        at com.heroku.sdk.deploy.App.deploy(App.java:61)
        at com.heroku.sdk.deploy.DeployJar.deploy(DeployJar.java:29)
        at com.heroku.sdk.deploy.DeployJar.main(DeployJar.java:104)
```

**Comment by jkutner** [comment]
see also https://github.com/heroku/heroku-maven-plugin/issues/26 (which is the underlying problem)

**Comment by jkutner** [comment]
@cobour in the latest version of the plugin, it should support `HTTP_PROXY` as described in [CLI Usage](https://devcenter.heroku.com/articles/using-the-cli#using-an-http-proxy). You may need to reinstall heroku-deploy for it to work.

Please give this a try and let me know if you still have trouble.

**Comment by cobour** [comment]
Works as expected now. Thank you!
